Exception: Replace core_esp8266_postmortem.cpp within framwork with own module.
The device is mostly located in the fuse box without any connected
computer.
The serial of the device is used to communicate with the electric meter
and dealing with baudrates of 300 or 9600 which disturbs the serial
exception dump.
Also working with low baudrates can trigger the hardware watchdog while
dumping the stack trace.

So: We capture exception information in our own module and write them to
the filesystem.

Wrapping the __wrap_system_restart_local() function using
'-Wl,--wrap=__wrap_system_restart_local' is not possible as the
system_restart_local() function is already wrapped within the original
framework.

We replace the original core_esp8266_postmortem.cpp while compiling this
project using
'pre:pio-scripts/replace_freamwork_core_esp8266_postmortem.py'